export default [
  {
    jugador: "Agostina Zorzón",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Cristina Cañizales",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Pierina Tufillaro",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Nico Dominguez",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Andrés Cañizales",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Lola Zorzón",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
  {
    jugador: "Rocky Cañizales",
    goles: 50,
    gol6m: 17,
    gol9m: 33,
    golContra: 15,
    golPenal: 7,
    erradas: 3,
    atajadas: 20,
    robadas: 26,
    perdidas: 22,
    efectividad: 60,
  },
];
