export default [
  {
    jugador: "Agostina Zorzón",
    resistencia: 80,
    velocidad: 70,
    saltoAlto: 1,
    saltoLargo: 2,
  },
  {
    jugador: "Cristina Cañizales",
    resistencia: 10,
    velocidad: 20,
    saltoAlto: 1,
    saltoLargo: 1,
  },
  {
    jugador: "Pierina Tufillaro",
    resistencia: 70,
    velocidad: 60,
    saltoAlto: 1,
    saltoLargo: 2,
  },
  {
    jugador: "Nicolás Domínguez",
    resistencia: 50,
    velocidad: 50,
    saltoAlto: 1,
    saltoLargo: 1,
  },
  {
    jugador: "Andrés Cañizales",
    resistencia: 50,
    velocidad: 50,
    saltoAlto: 1,
    saltoLargo: 1,
  },
  {
    jugador: "Lola Zorzón",
    resistencia: 50,
    velocidad: 50,
    saltoAlto: 1,
    saltoLargo: 1,
  },
  {
    jugador: "Rocky Cañizales",
    resistencia: 50,
    velocidad: 50,
    saltoAlto: 1,
    saltoLargo: 1,
  },
];
